version: "3.9"

services:
  client:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  server:
    build:
      context: ./server    
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
